### ISSUE TITLE
Linux install page is misleading

### ISSUE THREAD

**Issue by PunkPun** [OpenRA/OpenRAWebsiteV3#48]
<img width="973" alt="Screenshot 2023-09-07 at 18 22 47" src="https://github.com/OpenRA/OpenRAWebsiteV3/assets/37534529/c8966050-d7fa-4868-a0f7-e4613625b546">

https://github.com/probonopd/go-appimage

**Comment by PunkPun** [comment]
https://github.com/probonopd/go-appimage

**Comment by pchote** [comment]
go-appimage didn't actually work the last I looked at it (which was admittedly a long time ago now). appimaged was "deprecated" without a functional replacement in place.

**Comment by dragunoff** [comment]
> go-appimage didn't actually work the last I looked at it (which was admittedly a long time ago now). appimaged was "deprecated" without a functional replacement in place, and still works just fine.

I use go-appimage and it works for join links and desktop integration.

**Comment by Mailaender** [comment]
https://github.com/probonopd/go-appimage/releases has no proper versioning and https://repology.org/projects/?search=go-appimage is not included in any Linux distribution so far, so I am closing this as invalid.
